[licenses]
unlicensed = "deny"
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "allow"
confidence-threshold = 0.8

[licenses.private]
ignore = true

[bans]
multiple-versions = "allow"

[sources.allow-org]
github = ["Absolucy"]
