#define aneri_file_exists(file)				ANERI_CALL("file_exists", "[file]")
#define aneri_file_read(file)				ANERI_CALL("file_read", "[file]")
#define aneri_file_write(data, file)		ANERI_CALL("file_write", "[file]", "[data]")
#define aneri_file_append(data, file)		ANERI_CALL("file_append", "[file]", "[data]")
#define aneri_file_get_line_count(file)		ANERI_CALL("file_get_line_count", "[file]")
#define aneri_file_seek_line(file, line)	ANERI_CALL("file_seek", "[file]", line)
#define aneri_file_delete(file)				ANERI_CALL("file_delete", "[file]")
#define aneri_mkdir(path)					ANERI_CALL("mkdir", "[path]")
#define aneri_rmdir(path)					ANERI_CALL("rmdir", "[path]")
