#define aneri_file_exists(path)				(ANERI_CALL("file_exists", path))
#define aneri_file_read(path)				(ANERI_CALL("file_read", path))
#define aneri_file_write(path, data)		(ANERI_CALL("file_write", path, data))
#define aneri_file_append(path, data)		(ANERI_CALL("file_append", path, data))
#define aneri_file_get_line_count(path)		(ANERI_CALL("file_get_line_count", path))
#define aneri_file_seek_line(path, line)	(ANERI_CALL("file_seek_line", path, line))
#define aneri_file_delete(path)				(ANERI_CALL("file_delete", path))
#define aneri_mkdir(path)					(ANERI_CALL("mkdir", path))
#define aneri_rmdir(path)					(ANERI_CALL("rmdir", path))
