[package]
name = "aneri-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
meowtonin = { workspace = true }
slotmap = "1"
static_init = { version = "1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }

[features]
runtime = ["tokio", "static_init"]
